# Required to make Springdoc handling forward headers correctly when native compiled
server.forward-headers-strategy: framework

# Required to make the Spring AOT engine generate the appropriate infrastructure for a separate management port, prometheus and K8S probes at build time
management.server.port: 9009
management.endpoint.health.probes.enabled: true
management.endpoints.web.exposure.include: health,info,circuitbreakerevents,prometheus

# Required to make the Spring AOT engine generate a ReactiveJwtDecoder for the OIDC Issuer
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://someissuer

# See https://github.com/springdoc/springdoc-openapi/issues/1284#issuecomment-1279854219
springdoc.enable-native-support: true

# Native Compile: Point out that RabbitMQ is to be used when performing the native compile
spring.cloud.stream.defaultBinder: rabbit

# Native Compile: Required to disable the health check of RabbitMQ when using Kafka
# management.health.rabbit.enabled: false

# Native Compile: Required to disable the health check of Kafka when using RabbitMQ
management.health.kafka.enabled: false

# Native Compile: Required to get the Circuit Breaker's healthcheck work properly
management.health.circuitbreakers.enabled: true

